version: '3.1'

services:
  server:
    depends_on:
      - mysql
    build:
      context: ./server
    volumes:
      - ./server:/var/www/html/
    ports:
      - "8080:80"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - server

  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fumo_plush_store
      MYSQL_USER: user
      MYSQL_PASSWORD: 1111
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./fumodb_structure.sql:/docker-entrypoint-initdb.d/fumodb_structure.sql
